import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {




  return (
    <div className={styles.container}>
      <Head>
        <title>SimpleRacer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>



      <main className={styles.main}>
        <div className="header-container px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
          <h1 className="display-4">SimpleRacer!</h1>
          <p className="lead">Lag dine egne løp eller ritt, og la folk melde seg på!</p>
        </div>
        <div className={styles.actionbuttons}>
          <Link href="/races/new"><a className="btn btn-primary mx-4 my-2">Lag ny event</a></Link>
          <Link href="/races/new"><a className="btn btn-outline-primary mx-4 my-2">Se alle eventer</a></Link>
        </div>
      </main>

      <footer className={styles.footer}>
        GladLad Corona Production
      </footer>
    </div>
  )
}

export default Home
